version: 0.2
env:
  secrets-manager:
    DOCKERHUB_PASS: "/dockerhub/credentials:password"
    DOCKERHUB_USERNAME: "/dockerhub/credentials:username"


phases:
  install:
    commands:
      - echo pre_build step...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo image is $DOCKERHUB_USERNAME/$IMAGE_REPO_NAME:$IMAGE_TAG$CODEBUILD_BUILD_NUMBER
      - docker build -t $DOCKERHUB_USERNAME/$IMAGE_REPO_NAME:$IMAGE_TAG$CODEBUILD_BUILD_NUMBER .
      - docker tag $DOCKERHUB_USERNAME/$IMAGE_REPO_NAME:$IMAGE_TAG$CODEBUILD_BUILD_NUMBER $DOCKERHUB_USERNAME/$IMAGE_REPO_NAME:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $DOCKERHUB_USERNAME/$IMAGE_REPO_NAME:$IMAGE_TAG$CODEBUILD_BUILD_NUMBER
      - docker push $DOCKERHUB_USERNAME/$IMAGE_REPO_NAME:latest