apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekscost-deployment
  namespace : ekscost
  labels:
    app: ekscost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ekscost
  template:
    metadata:
      labels:
        app: ekscost
    spec:
      serviceAccountName: ekscost-sa
      containers:
      - name: ekscost
        image: lldhbm/ekscost:0.9
        ports:
        - containerPort: 80
#        env:
#        - name: AWS_DEFAULT_REGION
#          value: us-east-1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-info-reader
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-info-reader
subjects:
- kind: ServiceAccount
  name: ekscost-sa
  namespace: ekscost
roleRef:
  kind: ClusterRole
  name: cluster-info-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ekscost-sa
  namespace: ekscost
