apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekscost-deployment
  namespace : ekscost
  labels:
    app: ekscost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ekscost
  template:
    metadata:
      labels:
        app: ekscost
    spec:
      serviceAccountName: ekscost-sa
      containers:
      - name: ekscost
        image: lldhbm/ekscost:0.98
        resources:
          limits:
            cpu: "2"
            memory: 512Mi
          requests:
            cpu: "1"
            memory: 256Mi
        volumeMounts:
          - mountPath: /ekscost/config
            name: ekscost-config
            readOnly: true
      volumes:
        - configMap:
            name: ekscost-cm
          name: ekscost-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ekscost
  name: ekscost-cm
data:
  ekscost_config: |-
    TIMESTREAM_REGION = "us-east-1"
    DATABASE_NAME = "ekscost"
    CLUSTER_NAME = "eks-dev"
    TABLE_POD = "pod_info"
    TABLE_NODE = "node_info"
    INTERVAL_POD = 30
    INTERVAL_NODE = 60
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-info-reader
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-info-reader
subjects:
- kind: ServiceAccount
  name: ekscost-sa
  namespace: ekscost
roleRef:
  kind: ClusterRole
  name: cluster-info-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ekscost-sa
  namespace: ekscost
