DATABASE_NAME = "ekscost"
CLUSTER_NAME = "eks-dev"
# TABLE_POD = "dev_node_info"
# TABLE_NODE = "dev_node_info"
TABLE_POD = "pod_info"
TABLE_NODE = "node_info"
INTERVAL_POD = 5
INTERVAL_NODE = 10
TIMESTREAM_REGION="us-east-1"